import { mutationGeneric as mutation, queryGeneric as query } from "convex/server";
import { v } from "convex/values";

type UiStringSeed = {
  page: string;
  key: string;
  locale: "ja" | "en" | "zh" | "hi";
  text: string;
};

const JA_UI_STRINGS: UiStringSeed[] = [
  { page: "common_nav", key: "chat", locale: "ja", text: "みこと書き" },
  { page: "common_nav", key: "announcements", locale: "ja", text: "みちしるべ" },
  { page: "common_nav", key: "diary", locale: "ja", text: "日の結び" },
  { page: "common_nav", key: "profile", locale: "ja", text: "身支度" },

  { page: "chat", key: "title", locale: "ja", text: "みこと書き" },
  { page: "chat", key: "subtitle", locale: "ja", text: "1日3回、出来事や思いを記してください。" },
  { page: "chat", key: "group_unjoined", locale: "ja", text: "グループ未参加" },
  { page: "chat", key: "select_group_sr", locale: "ja", text: "チャットを選択" },
  { page: "chat", key: "status_report", locale: "ja", text: "Status Report" },
  { page: "chat", key: "daily_remaining_tpl", locale: "ja", text: "今日の残り投稿: あと{remaining} 回" },
  { page: "chat", key: "limit_label", locale: "ja", text: "LIMIT" },
  { page: "chat", key: "max_chars", locale: "ja", text: "1回につき200文字以内" },
  { page: "chat", key: "not_joined_title", locale: "ja", text: "まだグループに参加していません" },
  {
    page: "chat",
    key: "not_joined_desc",
    locale: "ja",
    text: "管理者からの招待リンクを開いて参加するか、プロフィール画面から新しいグループを作成してください。",
  },
  { page: "chat", key: "loading_guardian", locale: "ja", text: "ルフィが確認中..." },
  { page: "chat", key: "compose_placeholder", locale: "ja", text: "想いを言葉にしよう..." },
  { page: "chat", key: "error_daily_limit", locale: "ja", text: "今日の投稿回数上限に達しました。" },
  { page: "chat", key: "error_send", locale: "ja", text: "送信に失敗しました。" },
  { page: "chat", key: "error_switch", locale: "ja", text: "チャットの切り替えに失敗しました。" },
  { page: "chat", key: "error_like", locale: "ja", text: "ハートの更新に失敗しました。" },
  { page: "chat", key: "like_aria", locale: "ja", text: "AIファシリテーターの発言にハート" },
  { page: "chat", key: "like_title", locale: "ja", text: "この発言を次回の口調参考にする" },
  { page: "chat", key: "point_suffix", locale: "ja", text: "徳" },

  { page: "announcements", key: "title", locale: "ja", text: "みちしるべ" },
  {
    page: "announcements",
    key: "subtitle",
    locale: "ja",
    text: "語り合った時間のなかから、忘れてはならない明日へ繋ぐべき種を見つけます。",
  },
  { page: "announcements", key: "group_unjoined", locale: "ja", text: "グループ未参加" },
  { page: "announcements", key: "select_group_sr", locale: "ja", text: "チャットを選択" },
  { page: "announcements", key: "tasks_title", locale: "ja", text: "抽出された任務" },
  { page: "announcements", key: "tasks_badge", locale: "ja", text: "Active Tasks" },
  {
    page: "announcements",
    key: "tasks_desc",
    locale: "ja",
    text: "AIファシリテーターがチャットから重要な情報を抜き出しました。\nこれらを完了して「徳」を積みましょう。",
  },
  { page: "announcements", key: "tasks_desc_empty", locale: "ja", text: "現在、連絡事項はありません。" },
  { page: "announcements", key: "no_group_desc", locale: "ja", text: "グループに参加すると重要連絡が表示されます。" },
  { page: "announcements", key: "due_prefix", locale: "ja", text: "期限" },
  { page: "announcements", key: "importance_prefix", locale: "ja", text: "重要度" },
  { page: "announcements", key: "summary_badge", locale: "ja", text: "Guardian Summary" },
  { page: "announcements", key: "chance_title", locale: "ja", text: "今日の徳ポイント獲得チャンス" },
  {
    page: "announcements",
    key: "chance_desc",
    locale: "ja",
    text: "任務を完了して報告すると、AIファシリテーターが追加の徳を付与します。完了報告は投稿回数を消費しません。",
  },
  { page: "announcements", key: "write_report", locale: "ja", text: "完了報告を書く" },
  { page: "announcements", key: "report_target_label", locale: "ja", text: "報告対象" },
  { page: "announcements", key: "report_placeholder", locale: "ja", text: "完了内容を入力してください（8文字以上）" },
  { page: "announcements", key: "report_submitting", locale: "ja", text: "送信中..." },
  { page: "announcements", key: "report_done_badge", locale: "ja", text: "報告済み" },
  { page: "announcements", key: "close_button", locale: "ja", text: "掲示終了" },
  { page: "announcements", key: "close_submitting", locale: "ja", text: "処理中..." },
  { page: "announcements", key: "close_error", locale: "ja", text: "掲示終了に失敗しました。" },
  {
    page: "announcements",
    key: "close_success",
    locale: "ja",
    text: "期限未設定の連絡を掲示終了しました。",
  },
  { page: "announcements", key: "empty_title", locale: "ja", text: "連絡事項はありません" },
  {
    page: "announcements",
    key: "empty_desc",
    locale: "ja",
    text: "新しい重要連絡が投稿されると、ここに表示されます。",
  },
  { page: "announcements", key: "report_no_tasks", locale: "ja", text: "現在、報告できる連絡事項はありません。" },
  { page: "announcements", key: "report_select_error", locale: "ja", text: "連絡事項を選択してください。" },
  {
    page: "announcements",
    key: "report_success_tpl",
    locale: "ja",
    text: "完了報告を投稿しました（+{points}徳）。みこと書きに反映されます。",
  },
  { page: "announcements", key: "report_char_count_tpl", locale: "ja", text: "{count}/{max}" },
  { page: "announcements", key: "error_switch", locale: "ja", text: "チャットの切り替えに失敗しました。" },

  { page: "diary", key: "title", locale: "ja", text: "日の結び" },
  {
    page: "diary",
    key: "subtitle",
    locale: "ja",
    text: "みこと書きが更新されるその前に。想いを一束の記憶として留めます。",
  },
  { page: "diary", key: "group_unjoined", locale: "ja", text: "グループ未参加" },
  { page: "diary", key: "select_group_sr", locale: "ja", text: "チャットを選択" },
  { page: "diary", key: "archive_badge", locale: "ja", text: "Daily Archive" },
  { page: "diary", key: "date_record_tpl", locale: "ja", text: "{date} の記録" },
  { page: "diary", key: "date_missing_tpl", locale: "ja", text: "{date} の記録はありません" },
  { page: "diary", key: "date_loading", locale: "ja", text: "日付を読み込み中" },
  { page: "diary", key: "back_latest", locale: "ja", text: "最新表示に戻す" },
  {
    page: "diary",
    key: "auto_note",
    locale: "ja",
    text: "要約は毎日23:55ごろに自動作成され、0:00にチャット表示がリセットされます。",
  },
  { page: "diary", key: "no_group_desc", locale: "ja", text: "グループに参加すると日誌が表示されます。" },
  { page: "diary", key: "memo_badge", locale: "ja", text: "Guardian Memo" },
  { page: "diary", key: "no_diary", locale: "ja", text: "日誌がまだありません。" },
  { page: "diary", key: "emotion_title", locale: "ja", text: "感情の温度" },
  { page: "diary", key: "pulse_badge", locale: "ja", text: "Pulse" },
  { page: "diary", key: "safety_title", locale: "ja", text: "安心感" },
  { page: "diary", key: "safety_desc", locale: "ja", text: "配慮のある言葉が増加" },
  { page: "diary", key: "activity_title", locale: "ja", text: "活発さ" },
  { page: "diary", key: "activity_desc", locale: "ja", text: "質問・提案が中心" },
  { page: "diary", key: "alerts_title", locale: "ja", text: "注意信号" },
  { page: "diary", key: "alerts_desc", locale: "ja", text: "早期ケアで解決済み" },
  { page: "diary", key: "alerts_suffix", locale: "ja", text: "件" },
  { page: "diary", key: "error_switch", locale: "ja", text: "チャットの切り替えに失敗しました。" },

  { page: "profile", key: "title", locale: "ja", text: "身支度" },
  {
    page: "profile",
    key: "subtitle",
    locale: "ja",
    text: "心地よい交流を支えるための準備をここで行います。",
  },
  { page: "profile", key: "group_unjoined", locale: "ja", text: "グループ未参加" },
  { page: "profile", key: "select_group_sr", locale: "ja", text: "チャットを選択" },
  { page: "profile", key: "points_title", locale: "ja", text: "徳ポイント" },
  { page: "profile", key: "post_count_title", locale: "ja", text: "投稿回数" },
  { page: "profile", key: "weekly_title", locale: "ja", text: "今週の軌跡" },
  { page: "profile", key: "weekly_badge", locale: "ja", text: "Progress" },
  { page: "profile", key: "weekly_positive", locale: "ja", text: "ポジティブ投稿" },
  { page: "profile", key: "weekly_announcement", locale: "ja", text: "重要連絡共有" },
  { page: "profile", key: "weekly_ai_follow", locale: "ja", text: "AIフォロー" },
  { page: "profile", key: "message_title", locale: "ja", text: "メッセージ" },
  { page: "profile", key: "message_badge", locale: "ja", text: "Guidance" },
  { page: "profile", key: "edit_title", locale: "ja", text: "プロフィール編集" },
  { page: "profile", key: "edit_badge", locale: "ja", text: "Edit" },
  { page: "profile", key: "edit_name_label", locale: "ja", text: "名前" },
  { page: "profile", key: "edit_guardian_id_label", locale: "ja", text: "Guardian ID (@id)" },
  { page: "profile", key: "edit_guardian_id_placeholder", locale: "ja", text: "@kotonoha" },
  { page: "profile", key: "edit_class_label", locale: "ja", text: "所属" },
  { page: "profile", key: "edit_message_label", locale: "ja", text: "メッセージ" },
  { page: "profile", key: "save_profile", locale: "ja", text: "プロフィールを保存" },
  { page: "profile", key: "saving_profile", locale: "ja", text: "保存中..." },
  { page: "profile", key: "saved_profile", locale: "ja", text: "プロフィールを更新しました。" },
  { page: "profile", key: "groups_title", locale: "ja", text: "グループ管理" },
  { page: "profile", key: "groups_badge", locale: "ja", text: "Groups" },
  { page: "profile", key: "common_save", locale: "ja", text: "保存" },
  { page: "profile", key: "common_change", locale: "ja", text: "変更" },
  { page: "profile", key: "error_preview", locale: "ja", text: "口調サンプルを生成できませんでした。" },
  { page: "profile", key: "error_create", locale: "ja", text: "作成に失敗しました。" },
  { page: "profile", key: "error_invite_create", locale: "ja", text: "招待作成に失敗しました。" },
  { page: "profile", key: "error_group_switch", locale: "ja", text: "グループ切り替えに失敗しました。" },
  { page: "profile", key: "error_daily_limit_update", locale: "ja", text: "投稿上限の更新に失敗しました。" },
  { page: "profile", key: "error_group_rename", locale: "ja", text: "グループ名の変更に失敗しました。" },
  { page: "profile", key: "error_transfer_admin", locale: "ja", text: "管理権限の委譲に失敗しました。" },
  { page: "profile", key: "error_group_description_update", locale: "ja", text: "グループ説明の更新に失敗しました。" },
  { page: "profile", key: "error_ai_settings_update", locale: "ja", text: "AI設定の更新に失敗しました。" },
  { page: "profile", key: "error_profile_update", locale: "ja", text: "プロフィール更新に失敗しました。" },
  { page: "profile", key: "group_manage_select_title", locale: "ja", text: "管理するチャット名（プルダウン）" },
  { page: "profile", key: "group_manage_select_hint", locale: "ja", text: "管理対象のチャットを選択してください。" },
  { page: "profile", key: "group_manage_no_joined_group", locale: "ja", text: "まだ参加しているチャットがありません。" },
  { page: "profile", key: "group_rename_title", locale: "ja", text: "グループ名変更" },
  { page: "profile", key: "group_rename_admin_only", locale: "ja", text: "グループ名は管理者のみ変更できます。" },
  { page: "profile", key: "group_description_title", locale: "ja", text: "グループ説明" },
  {
    page: "profile",
    key: "group_description_placeholder",
    locale: "ja",
    text: "例: 中学2年のクラス連絡用。提出物・持ち物・集合連絡を共有する目的。",
  },
  {
    page: "profile",
    key: "group_description_help",
    locale: "ja",
    text: "AIヒーローのコメント・抽出・要約の参考に使用されます。",
  },
  { page: "profile", key: "group_description_admin_only", locale: "ja", text: "グループ説明は管理者のみ変更できます。" },
  { page: "profile", key: "facilitator_title", locale: "ja", text: "AIファシリテーター設定" },
  { page: "profile", key: "facilitator_enable_label", locale: "ja", text: "このチャットでAIファシリテーターを有効化" },
  { page: "profile", key: "facilitator_name_label", locale: "ja", text: "名前" },
  { page: "profile", key: "facilitator_name_placeholder", locale: "ja", text: "例: ルフィ先生" },
  { page: "profile", key: "facilitator_preset_label", locale: "ja", text: "性格プリセット" },
  { page: "profile", key: "facilitator_preset_encouraging", locale: "ja", text: "励まし型" },
  { page: "profile", key: "facilitator_preset_watcher", locale: "ja", text: "見守り型" },
  { page: "profile", key: "facilitator_preset_facilitator", locale: "ja", text: "進行役型" },
  { page: "profile", key: "facilitator_preset_disciplined", locale: "ja", text: "規律型" },
  { page: "profile", key: "facilitator_gender_label", locale: "ja", text: "性別（任意）" },
  { page: "profile", key: "facilitator_gender_placeholder", locale: "ja", text: "例: 男性 / 女性 / 未設定" },
  { page: "profile", key: "facilitator_age_label", locale: "ja", text: "年齢（任意）" },
  { page: "profile", key: "facilitator_age_placeholder", locale: "ja", text: "例: 28" },
  { page: "profile", key: "facilitator_first_person_label", locale: "ja", text: "一人称（任意）" },
  { page: "profile", key: "facilitator_first_person_placeholder", locale: "ja", text: "例: わたし" },
  { page: "profile", key: "facilitator_tone_label", locale: "ja", text: "話し方（任意）" },
  { page: "profile", key: "facilitator_tone_placeholder", locale: "ja", text: "例: 丁寧 / フランク" },
  { page: "profile", key: "facilitator_bio_label", locale: "ja", text: "補足キャラ設定（任意）" },
  {
    page: "profile",
    key: "facilitator_bio_placeholder",
    locale: "ja",
    text: "例: 体育会系で短く背中を押す。連絡事項は明確に伝える。",
  },
  { page: "profile", key: "facilitator_preview_title", locale: "ja", text: "口調サンプル" },
  { page: "profile", key: "facilitator_preview_loading", locale: "ja", text: "管理AIがサンプルを作成中..." },
  { page: "profile", key: "facilitator_preview_empty", locale: "ja", text: "設定を入力するとここに表示されます。" },
  {
    page: "profile",
    key: "facilitator_hint",
    locale: "ja",
    text: "設定はこのチャット専用です。ルール判定を優先し、口調のみ反映します。",
  },
  { page: "profile", key: "facilitator_admin_only", locale: "ja", text: "AIファシリテーター設定は管理者のみ変更できます。" },
  { page: "profile", key: "daily_limit_title", locale: "ja", text: "日次投稿上限" },
  { page: "profile", key: "daily_limit_readonly_prefix", locale: "ja", text: "現在の上限" },
  { page: "profile", key: "daily_limit_readonly_suffix", locale: "ja", text: "回/日（変更は管理者のみ）" },
  { page: "profile", key: "invite_title", locale: "ja", text: "招待リンク" },
  { page: "profile", key: "invite_max_uses_label", locale: "ja", text: "利用回数" },
  { page: "profile", key: "invite_create_button", locale: "ja", text: "招待リンクを発行" },
  { page: "profile", key: "invite_created_suffix_prefix", locale: "ja", text: "（最大" },
  { page: "profile", key: "invite_created_suffix_suffix", locale: "ja", text: "回）" },
  { page: "profile", key: "invite_admin_only", locale: "ja", text: "招待リンクは管理者のみ発行できます。" },
  { page: "profile", key: "members_title", locale: "ja", text: "グループメンバー" },
  { page: "profile", key: "members_empty", locale: "ja", text: "メンバーがまだいません。" },
  { page: "profile", key: "members_select_group", locale: "ja", text: "グループを選択するとメンバーが表示されます。" },
  { page: "profile", key: "transfer_admin_title", locale: "ja", text: "管理権限の委譲" },
  { page: "profile", key: "transfer_admin_button", locale: "ja", text: "このユーザーに委譲" },
  { page: "profile", key: "transfer_admin_no_candidate", locale: "ja", text: "委譲可能なメンバーがいません。" },
  { page: "profile", key: "transfer_admin_admin_only", locale: "ja", text: "管理権限の委譲は管理者のみ実行できます。" },
  { page: "profile", key: "create_group_title", locale: "ja", text: "新しいグループを作成" },
  { page: "profile", key: "create_group_placeholder", locale: "ja", text: "例: 3年B組 チャット" },
  { page: "profile", key: "create_group_button_prefix", locale: "ja", text: "作成（" },
  { page: "profile", key: "create_group_button_suffix", locale: "ja", text: "徳消費）" },
  { page: "profile", key: "create_group_hint", locale: "ja", text: "一定量の徳ポイントを保有していると作成できます。" },

  { page: "invite", key: "title", locale: "ja", text: "招待リンク" },
  { page: "invite", key: "join_group_tpl", locale: "ja", text: "{groupName} に参加します。" },
  { page: "invite", key: "loading", locale: "ja", text: "招待情報を読み込み中..." },
  { page: "invite", key: "sign_needed", locale: "ja", text: "参加するにはサインインまたはサインアップしてください。" },
  { page: "invite", key: "sign_in", locale: "ja", text: "サインイン" },
  { page: "invite", key: "sign_up", locale: "ja", text: "新規登録" },
  { page: "invite", key: "joining", locale: "ja", text: "参加処理中..." },
  { page: "invite", key: "join", locale: "ja", text: "このクラスに参加" },
  { page: "invite", key: "error_expired", locale: "ja", text: "この招待リンクは期限切れです。" },
  { page: "invite", key: "error_join", locale: "ja", text: "参加に失敗しました。" },

  { page: "sign_in", key: "title", locale: "ja", text: "ことばむすび" },
  { page: "sign_in", key: "subtitle", locale: "ja", text: "日々の言葉や出来事を届けよう。" },
  { page: "sign_up", key: "title", locale: "ja", text: "言の葉ガーディアン" },
  { page: "sign_up", key: "subtitle", locale: "ja", text: "Google またはメールで登録し、クラスの言葉を守りましょう。" },
];

const EN_OVERRIDES: Record<string, string> = {
  "common_nav.chat": "Mikoto Notes",
  "common_nav.announcements": "Guideposts",
  "common_nav.diary": "Day Wrap",
  "common_nav.profile": "Setup",
  "chat.title": "Mikoto Notes",
  "chat.subtitle": "Post up to 3 times a day about your moments and thoughts.",
  "chat.group_unjoined": "No Group Joined",
  "chat.select_group_sr": "Select chat group",
  "chat.daily_remaining_tpl": "Remaining posts today: {remaining}",
  "chat.max_chars": "Up to 200 characters per post",
  "chat.not_joined_title": "You have not joined a group yet",
  "chat.not_joined_desc":
    "Open an invite link from an admin, or create a new group from Profile.",
  "chat.loading_guardian": "Facilitator is checking...",
  "chat.compose_placeholder": "Put your thoughts into words...",
  "chat.error_daily_limit": "You reached today\u2019s post limit.",
  "chat.error_send": "Failed to send.",
  "chat.error_switch": "Failed to switch chat.",
  "chat.error_like": "Failed to update heart.",
  "chat.like_aria": "Heart this AI facilitator message",
  "chat.like_title": "Use this message as tone reference next time",
  "chat.point_suffix": "pts",
  "announcements.title": "Guideposts",
  "announcements.subtitle":
    "Find the seeds from your conversations that should carry into tomorrow.",
  "announcements.group_unjoined": "No Group Joined",
  "announcements.select_group_sr": "Select chat group",
  "announcements.tasks_title": "Extracted Tasks",
  "announcements.tasks_desc":
    "The AI facilitator extracted important items from your chat. Complete them to earn points.",
  "announcements.tasks_desc_empty": "There are no announcements right now.",
  "announcements.no_group_desc":
    "Announcements appear after you join a group.",
  "announcements.due_prefix": "Due",
  "announcements.importance_prefix": "Priority",
  "announcements.chance_title": "Today\u2019s Point Opportunity",
  "announcements.chance_desc":
    "Report completed tasks to receive extra points from the AI facilitator. Completion reports do not consume daily post counts.",
  "announcements.write_report": "Write completion report",
  "announcements.report_target_label": "Report target",
  "announcements.report_placeholder": "Describe what you completed (8+ chars)",
  "announcements.report_submitting": "Submitting...",
  "announcements.report_done_badge": "Reported",
  "announcements.close_button": "Close Posting",
  "announcements.close_submitting": "Closing...",
  "announcements.close_error": "Failed to close posting.",
  "announcements.close_success": "Closed an undated announcement.",
  "announcements.empty_title": "No announcements",
  "announcements.empty_desc": "New important notices will appear here.",
  "announcements.report_no_tasks": "There are no announcement tasks to report now.",
  "announcements.report_select_error": "Please select an announcement.",
  "announcements.report_success_tpl":
    "Completion report posted (+{points} pts). It appears in Mikoto Notes.",
  "announcements.report_char_count_tpl": "{count}/{max}",
  "announcements.error_switch": "Failed to switch chat.",
  "diary.title": "Day Wrap",
  "diary.subtitle":
    "Before Mikoto Notes refreshes, keep your thoughts as one bundle of memory.",
  "diary.group_unjoined": "No Group Joined",
  "diary.select_group_sr": "Select chat group",
  "diary.date_record_tpl": "Record for {date}",
  "diary.date_missing_tpl": "No record for {date}",
  "diary.date_loading": "Loading date...",
  "diary.back_latest": "Back to latest",
  "diary.auto_note":
    "Summaries are auto-created around 23:55 and chat display resets at 00:00.",
  "diary.no_group_desc": "Diary appears after you join a group.",
  "diary.no_diary": "No diary yet.",
  "diary.emotion_title": "Emotion Temperature",
  "diary.safety_title": "Safety",
  "diary.safety_desc": "More considerate language",
  "diary.activity_title": "Activity",
  "diary.activity_desc": "Questions and proposals are active",
  "diary.alerts_title": "Alerts",
  "diary.alerts_desc": "Resolved with early care",
  "diary.alerts_suffix": "items",
  "diary.error_switch": "Failed to switch chat.",
  "profile.title": "Setup",
  "profile.subtitle": "Prepare for healthy, comfortable communication here.",
  "profile.group_unjoined": "No Group Joined",
  "profile.select_group_sr": "Select chat group",
  "profile.points_title": "Points",
  "profile.post_count_title": "Posts",
  "profile.weekly_title": "This Week",
  "profile.weekly_positive": "Positive posts",
  "profile.weekly_announcement": "Shared announcements",
  "profile.weekly_ai_follow": "AI follow-ups",
  "profile.message_title": "Message",
  "profile.edit_title": "Edit Profile",
  "profile.edit_name_label": "Name",
  "profile.edit_guardian_id_label": "Guardian ID (@id)",
  "profile.edit_guardian_id_placeholder": "@guardian",
  "profile.edit_class_label": "Affiliation",
  "profile.edit_message_label": "Message",
  "profile.save_profile": "Save profile",
  "profile.saving_profile": "Saving...",
  "profile.saved_profile": "Profile updated.",
  "profile.groups_title": "Group Management",
  "profile.common_save": "Save",
  "profile.common_change": "Change",
  "profile.error_preview": "Failed to generate speaking sample.",
  "profile.error_create": "Failed to create.",
  "profile.error_invite_create": "Failed to create invite.",
  "profile.error_group_switch": "Failed to switch group.",
  "profile.error_daily_limit_update": "Failed to update daily limit.",
  "profile.error_group_rename": "Failed to rename group.",
  "profile.error_transfer_admin": "Failed to transfer admin role.",
  "profile.error_group_description_update": "Failed to update group description.",
  "profile.error_ai_settings_update": "Failed to update AI settings.",
  "profile.error_profile_update": "Failed to update profile.",
  "profile.group_manage_select_title": "Select Managed Chat (Dropdown)",
  "profile.group_manage_select_hint": "Select a managed chat target.",
  "profile.group_manage_no_joined_group": "You have not joined any chats yet.",
  "profile.group_rename_title": "Rename Group",
  "profile.group_rename_admin_only": "Only admins can rename groups.",
  "profile.group_description_title": "Group Description",
  "profile.group_description_placeholder":
    "e.g. Class communication for Grade 8. Share deadlines and logistics.",
  "profile.group_description_help":
    "Used as context for AI comments, extraction, and summaries.",
  "profile.group_description_admin_only":
    "Only admins can edit the group description.",
  "profile.facilitator_title": "AI Facilitator Settings",
  "profile.facilitator_enable_label": "Enable AI facilitator in this chat",
  "profile.facilitator_name_label": "Name",
  "profile.facilitator_name_placeholder": "e.g. Ms. Luffy",
  "profile.facilitator_preset_label": "Personality Preset",
  "profile.facilitator_preset_encouraging": "Encouraging",
  "profile.facilitator_preset_watcher": "Watcher",
  "profile.facilitator_preset_facilitator": "Facilitator",
  "profile.facilitator_preset_disciplined": "Disciplined",
  "profile.facilitator_gender_label": "Gender (optional)",
  "profile.facilitator_gender_placeholder": "e.g. male / female / unset",
  "profile.facilitator_age_label": "Age (optional)",
  "profile.facilitator_age_placeholder": "e.g. 28",
  "profile.facilitator_first_person_label": "First person (optional)",
  "profile.facilitator_first_person_placeholder": "e.g. I",
  "profile.facilitator_tone_label": "Tone (optional)",
  "profile.facilitator_tone_placeholder": "e.g. polite / casual",
  "profile.facilitator_bio_label": "Character notes (optional)",
  "profile.facilitator_bio_placeholder":
    "e.g. Sports-minded, concise support, clear on announcements.",
  "profile.facilitator_preview_title": "Tone Sample",
  "profile.facilitator_preview_loading": "Generating sample...",
  "profile.facilitator_preview_empty": "A sample appears after entering settings.",
  "profile.facilitator_hint":
    "Settings are per-chat. Rule enforcement is prioritized over tone.",
  "profile.facilitator_admin_only": "Only admins can edit AI settings.",
  "profile.daily_limit_title": "Daily Post Limit",
  "profile.daily_limit_readonly_prefix": "Current limit",
  "profile.daily_limit_readonly_suffix": "posts/day (admins only)",
  "profile.invite_title": "Invite Link",
  "profile.invite_max_uses_label": "Max uses",
  "profile.invite_create_button": "Create invite link",
  "profile.invite_created_suffix_prefix": "(max ",
  "profile.invite_created_suffix_suffix": " uses)",
  "profile.invite_admin_only": "Only admins can issue invite links.",
  "profile.members_title": "Group Members",
  "profile.members_empty": "No members yet.",
  "profile.members_select_group": "Select a group to view members.",
  "profile.transfer_admin_title": "Transfer Admin Role",
  "profile.transfer_admin_button": "Transfer to this user",
  "profile.transfer_admin_no_candidate": "No eligible member to transfer.",
  "profile.transfer_admin_admin_only":
    "Only admins can transfer admin role.",
  "profile.create_group_title": "Create New Group",
  "profile.create_group_placeholder": "e.g. Grade 3-B Chat",
  "profile.create_group_button_prefix": "Create (",
  "profile.create_group_button_suffix": " point cost)",
  "profile.create_group_hint":
    "You can create a group when you have enough points.",
  "invite.title": "Invite Link",
  "invite.join_group_tpl": "Join {groupName}.",
  "invite.loading": "Loading invite info...",
  "invite.sign_needed": "Please sign in or sign up to join.",
  "invite.sign_in": "Sign In",
  "invite.sign_up": "Sign Up",
  "invite.joining": "Joining...",
  "invite.join": "Join this class",
  "invite.error_expired": "This invite link has expired.",
  "invite.error_join": "Failed to join.",
  "sign_in.title": "Kotonoha Guardian",
  "sign_in.subtitle":
    "Safely share your words in the class you joined via invite link.",
  "sign_up.title": "Kotonoha Guardian",
  "sign_up.subtitle":
    "Sign up with Google or email and protect class communication.",
};

const ZH_OVERRIDES: Record<string, string> = {
  "announcements.chance_desc": "完成任务并提交报告后，AI路飞会追加德分。完成报告不消耗每日发帖次数。",
  "announcements.chance_title": "今天有机会赚取美德积分",
  "announcements.due_prefix": "最后期限",
  "announcements.error_switch": "切换聊天失败。",
  "announcements.group_unjoined": "不参加团体",
  "announcements.importance_prefix": "重要性",
  "announcements.no_group_desc": "当您加入群组时，将会显示重要通知。",
  "announcements.report_char_count_tpl": "{count}/{max}",
  "announcements.report_done_badge": "已报告",
  "announcements.report_no_tasks": "目前没有可报告的连络事项。",
  "announcements.report_placeholder": "请输入完成内容（至少8个字）",
  "announcements.report_select_error": "请选择连络事项。",
  "announcements.report_submitting": "发送中...",
  "announcements.report_success_tpl": "已发布完成报告（+{points}德）。会显示在御言日记中。",
  "announcements.report_target_label": "报告对象",
  "announcements.close_button": "结束掲示",
  "announcements.close_submitting": "处理中...",
  "announcements.close_error": "结束掲示失败。",
  "announcements.close_success": "已结束未设期限的连络事项。",
  "announcements.empty_title": "暂无连络事项",
  "announcements.empty_desc": "有新的重要连络时，会显示在这里。",
  "announcements.select_group_sr": "选择聊天",
  "announcements.subtitle": "从我们谈话的那一刻起，我们就会找到我们永远不应该忘记的种子，并与明天联系起来。",
  "announcements.summary_badge": "守护者总结",
  "announcements.tasks_badge": "活动任务",
  "announcements.tasks_desc": "AI路飞从聊天中提取了重要信息。完成这些，积累“德”。",
  "announcements.tasks_desc_empty": "目前没有连络事项。",
  "announcements.tasks_title": "提取任务",
  "announcements.title": "道郡部",
  "announcements.write_report": "撰写完成报告",
  "chat.compose_placeholder": "让我们用语言表达我们的想法......",
  "chat.daily_remaining_tpl": "今天剩余帖子：{remaining} 次",
  "chat.error_daily_limit": "您已达到今天的帖子数量上限。",
  "chat.error_like": "心脏更新失败。",
  "chat.error_send": "发送失败。",
  "chat.error_switch": "切换聊天失败。",
  "chat.group_unjoined": "不参加团体",
  "chat.like_aria": "被AI辅导员的言论塑造成心形",
  "chat.like_title": "使用此声明作为您下一个语气的参考。",
  "chat.limit_label": "限制",
  "chat.loading_guardian": "路飞正在检查...",
  "chat.max_chars": "每次最多 200 个字符",
  "chat.not_joined_desc": "打开管理员的邀请链接加入，或从您的个人资料屏幕创建新群组。",
  "chat.not_joined_title": "还没有加入群组",
  "chat.point_suffix": "美德",
  "chat.select_group_sr": "选择聊天",
  "chat.status_report": "状态报告",
  "chat.subtitle": "每天写下你的事件和想法三次。",
  "chat.title": "美琴写作",
  "common_nav.announcements": "道郡部",
  "common_nav.chat": "美琴写作",
  "common_nav.diary": "当天的结",
  "common_nav.profile": "准备工作",
  "diary.activity_desc": "主要是问题和建议",
  "diary.activity_title": "热闹",
  "diary.alerts_desc": "通过早期护理解决",
  "diary.alerts_suffix": "主题",
  "diary.alerts_title": "警告信号",
  "diary.archive_badge": "每日档案",
  "diary.auto_note": "每天23:55左右自动创建摘要，0:00重置聊天显示。",
  "diary.back_latest": "刷新",
  "diary.date_loading": "装货日期",
  "diary.date_missing_tpl": "没有 {date} 的记录",
  "diary.date_record_tpl": "{date}的记录",
  "diary.emotion_title": "情绪温度",
  "diary.error_switch": "切换聊天失败。",
  "diary.group_unjoined": "不参加团体",
  "diary.memo_badge": "监护人备忘录",
  "diary.no_diary": "我还没有日记。",
  "diary.no_group_desc": "当您加入群组时，将会显示日记。",
  "diary.pulse_badge": "脉冲",
  "diary.safety_desc": "体贴的话语数量增加",
  "diary.safety_title": "安全感",
  "diary.select_group_sr": "选择聊天",
  "diary.subtitle": "在经文更新之前。将你的想法保留为记忆。",
  "diary.title": "当天的结",
  "invite.error_expired": "此邀请链接已过期。",
  "invite.error_join": "参与失败。",
  "invite.join": "加入这个班级",
  "invite.join_group_tpl": "加入{groupName}。",
  "invite.joining": "参与处理...",
  "invite.loading": "正在加载邀请信息...",
  "invite.sign_in": "登入",
  "invite.sign_needed": "请登录或注册参与。",
  "invite.sign_up": "新注册",
  "invite.title": "邀请链接",
  "profile.common_change": "改变",
  "profile.common_save": "保持",
  "profile.create_group_button_prefix": "创造（",
  "profile.create_group_button_suffix": "美德消费）",
  "profile.create_group_hint": "如果你有一定数量的美德点，你就可以创建一个。",
  "profile.create_group_placeholder": "示例：3B 类聊天",
  "profile.create_group_title": "创建新组",
  "profile.daily_limit_readonly_prefix": "当前上限",
  "profile.daily_limit_readonly_suffix": "次/天（只能由管理员更改）",
  "profile.daily_limit_title": "每日发帖限额",
  "profile.edit_badge": "编辑",
  "profile.edit_class_label": "联系",
  "profile.edit_guardian_id_label": "监护人 ID (@id)",
  "profile.edit_guardian_id_placeholder": "@kotonoha",
  "profile.edit_message_label": "信息",
  "profile.edit_name_label": "姓名",
  "profile.edit_title": "编辑个人资料",
  "profile.error_ai_settings_update": "无法更新 AI 设置。",
  "profile.error_create": "创建失败。",
  "profile.error_daily_limit_update": "无法更新发帖限制。",
  "profile.error_group_description_update": "无法更新组描述。",
  "profile.error_group_rename": "更改群组名称失败。",
  "profile.error_group_switch": "组切换失败。",
  "profile.error_invite_create": "创建邀请失败。",
  "profile.error_preview": "无法生成音调样本。",
  "profile.error_profile_update": "个人资料更新失败。",
  "profile.error_transfer_admin": "管理权限委派失败。",
  "profile.facilitator_admin_only": "只有管​​理员可以更改 AI facilitator 设置。",
  "profile.facilitator_age_label": "年龄（可选）",
  "profile.facilitator_age_placeholder": "示例：28",
  "profile.facilitator_bio_label": "补充字符设置（可选）",
  "profile.facilitator_bio_placeholder": "示例：运动员短暂地拍拍他的背。将要沟通的事项沟通清楚。",
  "profile.facilitator_enable_label": "在此聊天中启用人工智能辅助器",
  "profile.facilitator_first_person_label": "第一人称（可选）",
  "profile.facilitator_first_person_placeholder": "例子：我",
  "profile.facilitator_gender_label": "性别（可选）",
  "profile.facilitator_gender_placeholder": "示例：男/女/未设置",
  "profile.facilitator_hint": "这些设置仅适用于本次聊天。优先规则判断，只体现语气。",
  "profile.facilitator_name_label": "姓名",
  "profile.facilitator_name_placeholder": "例子：路飞老师",
  "profile.facilitator_preset_disciplined": "学科类型",
  "profile.facilitator_preset_encouraging": "鼓励型",
  "profile.facilitator_preset_facilitator": "促进者类型",
  "profile.facilitator_preset_label": "个性预设",
  "profile.facilitator_preset_watcher": "手表类型",
  "profile.facilitator_preview_empty": "输入设置后，它们将出现在此处。",
  "profile.facilitator_preview_loading": "管理 AI 正在创建一个示例...",
  "profile.facilitator_preview_title": "音调样本",
  "profile.facilitator_title": "AI 促进者设置",
  "profile.facilitator_tone_label": "如何说话（可选）",
  "profile.facilitator_tone_placeholder": "示例：礼貌/坦率",
  "profile.group_description_admin_only": "组描述只能由管理员更改。",
  "profile.group_description_help": "用作AI英雄评论、摘录、总结的参考。",
  "profile.group_description_placeholder": "例：初中二年级课堂交流。共享提交内容、所有物和群组通信的目的。",
  "profile.group_description_title": "团体描述",
  "profile.group_manage_no_joined_group": "您还没有加入任何聊天。",
  "profile.group_manage_select_hint": "选择您要管理的聊天。",
  "profile.group_manage_select_title": "要管理的聊天名称（下拉列表）",
  "profile.group_rename_admin_only": "组名称只能由管理员更改。",
  "profile.group_rename_title": "团体名称变更",
  "profile.group_unjoined": "不参加团体",
  "profile.groups_badge": "团体",
  "profile.groups_title": "集团管理",
  "profile.invite_admin_only": "邀请链接只能由管理员发出。",
  "profile.invite_create_button": "发出邀请链接",
  "profile.invite_created_suffix_prefix": "（最大限度",
  "profile.invite_created_suffix_suffix": "次）",
  "profile.invite_max_uses_label": "使用次数",
  "profile.invite_title": "邀请链接",
  "profile.members_empty": "还没有会员。",
  "profile.members_select_group": "选择一个组以显示其成员。",
  "profile.members_title": "小组成员",
  "profile.message_badge": "指导",
  "profile.message_title": "信息",
  "profile.points_title": "美德点",
  "profile.post_count_title": "帖子数量",
  "profile.save_profile": "保存个人资料",
  "profile.saved_profile": "我的个人资料已更新。",
  "profile.saving_profile": "保存...",
  "profile.select_group_sr": "选择聊天",
  "profile.subtitle": "在这里，我们将做好准备，以支持愉快的互动。",
  "profile.title": "准备工作",
  "profile.transfer_admin_admin_only": "只有管​​理员可以委派管理权限。",
  "profile.transfer_admin_button": "委托给该用户",
  "profile.transfer_admin_no_candidate": "没有可供委派的成员。",
  "profile.transfer_admin_title": "下放行政权力",
  "profile.weekly_ai_follow": "人工智能跟随",
  "profile.weekly_announcement": "重要讯息分享",
  "profile.weekly_badge": "进步",
  "profile.weekly_positive": "积极的帖子",
  "profile.weekly_title": "本周轨迹",
  "sign_in.subtitle": "使用邀请链接放心地将您的消息传递给您加入的班级。",
  "sign_in.title": "言语的守护者",
  "sign_up.subtitle": "在 Google 或电子邮件上注册并保留您的课堂用语。",
  "sign_up.title": "言语的守护者",
};

const HI_OVERRIDES: Record<string, string> = {
  "announcements.chance_desc": "मिशन पूरा करके रिपोर्ट करने पर एआई लफी अतिरिक्त सद्गुण अंक देगा। पूर्णता रिपोर्ट दैनिक पोस्ट गिनती में शामिल नहीं होती।",
  "announcements.chance_title": "आज पुण्य अंक अर्जित करने का मौका",
  "announcements.due_prefix": "अंतिम तारीख",
  "announcements.error_switch": "चैट स्विच करने में विफल.",
  "announcements.group_unjoined": "समूह में भाग नहीं लेना",
  "announcements.importance_prefix": "महत्त्व",
  "announcements.no_group_desc": "जब आप समूह में शामिल होंगे तो महत्वपूर्ण सूचनाएं प्रदर्शित की जाएंगी।",
  "announcements.report_char_count_tpl": "{count}/{max}",
  "announcements.report_done_badge": "रिपोर्ट हो चुका",
  "announcements.report_no_tasks": "अभी रिपोर्ट करने के लिए कोई सूचना नहीं है।",
  "announcements.report_placeholder": "पूरा किया गया विवरण लिखें (कम से कम 8 अक्षर)",
  "announcements.report_select_error": "कृपया एक सूचना चुनें।",
  "announcements.report_submitting": "भेजा जा रहा है...",
  "announcements.report_success_tpl": "पूर्णता रिपोर्ट पोस्ट हो गई (+{points} सद्गुण)। यह मिकोतो लेखन में दिखेगी।",
  "announcements.report_target_label": "रिपोर्ट लक्ष्य",
  "announcements.close_button": "प्रदर्शन समाप्त",
  "announcements.close_submitting": "प्रक्रिया जारी...",
  "announcements.close_error": "प्रदर्शन समाप्त करने में विफल.",
  "announcements.close_success": "बिना समय-सीमा वाली सूचना बंद कर दी गई.",
  "announcements.empty_title": "कोई घोषणाएं नहीं",
  "announcements.empty_desc": "नई महत्वपूर्ण सूचनाएं यहां दिखाई देंगी।",
  "announcements.select_group_sr": "चैट चुनें",
  "announcements.subtitle": "जब से हमने बात की है, हमें ऐसे बीज मिलेंगे जिन्हें हमें कभी नहीं भूलना चाहिए और आने वाले कल से जुड़ना चाहिए।",
  "announcements.summary_badge": "अभिभावक सारांश",
  "announcements.tasks_badge": "सक्रिय कार्य",
  "announcements.tasks_desc": "एआई लफी ने चैट से महत्वपूर्ण जानकारी निकाली। इन्हें पूरा करें और \"पुण्य\" अर्जित करें।",
  "announcements.tasks_desc_empty": "अभी कोई घोषणाएं नहीं हैं।",
  "announcements.tasks_title": "निकाला गया मिशन",
  "announcements.title": "मिशिशिर्बे",
  "announcements.write_report": "एक पूर्णता रिपोर्ट लिखें",
  "chat.compose_placeholder": "आइए अपने विचारों को शब्दों में पिरोएं...",
  "chat.daily_remaining_tpl": "आज के लिए शेष पोस्ट: {remaining} बार",
  "chat.error_daily_limit": "आप आज के लिए पोस्ट की अधिकतम संख्या तक पहुंच गए हैं.",
  "chat.error_like": "हृदय अद्यतन विफल रहा.",
  "chat.error_send": "भेजना विफल रहा.",
  "chat.error_switch": "चैट स्विच करने में विफल.",
  "chat.group_unjoined": "समूह में भाग नहीं लेना",
  "chat.like_aria": "एआई फैसिलिटेटर की टिप्पणियों से दिल को आकार मिला",
  "chat.like_title": "इस कथन को अपने अगले स्वर के संदर्भ के रूप में उपयोग करें।",
  "chat.limit_label": "आप LIMIT",
  "chat.loading_guardian": "लफ़ी जाँच कर रहा है...",
  "chat.max_chars": "हर बार 200 अक्षर तक",
  "chat.not_joined_desc": "शामिल होने के लिए व्यवस्थापक से आमंत्रण लिंक खोलें, या अपनी प्रोफ़ाइल स्क्रीन से एक नया समूह बनाएं।",
  "chat.not_joined_title": "अभी तक किसी समूह में शामिल नहीं हुए हैं",
  "chat.point_suffix": "गुण",
  "chat.select_group_sr": "चैट चुनें",
  "chat.status_report": "स्थिति रिपोर्ट",
  "chat.subtitle": "अपनी घटनाओं और विचारों को दिन में तीन बार लिखें।",
  "chat.title": "मिकोटो लेखन",
  "common_nav.announcements": "मिशिशिर्बे",
  "common_nav.chat": "मिकोटो लेखन",
  "common_nav.diary": "दिन की गाँठ",
  "common_nav.profile": "तैयार हो रहे",
  "diary.activity_desc": "मुख्यतः प्रश्न एवं सुझाव",
  "diary.activity_title": "जीवंतता",
  "diary.alerts_desc": "शीघ्र देखभाल से समाधान हो गया",
  "diary.alerts_suffix": "विषय",
  "diary.alerts_title": "सावधानी संकेत",
  "diary.archive_badge": "दैनिक पुरालेख",
  "diary.auto_note": "प्रत्येक दिन लगभग 23:55 पर एक सारांश स्वचालित रूप से बनाया जाएगा, और चैट डिस्प्ले 0:00 पर रीसेट हो जाएगा।",
  "diary.back_latest": "ताज़ा करना",
  "diary.date_loading": "लदान दिनांक",
  "diary.date_missing_tpl": "{date} के लिए कोई रिकॉर्ड नहीं हैं",
  "diary.date_record_tpl": "{date} का रिकॉर्ड",
  "diary.emotion_title": "भावनात्मक तापमान",
  "diary.error_switch": "चैट स्विच करने में विफल.",
  "diary.group_unjoined": "समूह में भाग नहीं लेना",
  "diary.memo_badge": "अभिभावक ज्ञापन",
  "diary.no_diary": "मेरे पास अभी तक कोई पत्रिका नहीं है.",
  "diary.no_group_desc": "जब आप किसी समूह में शामिल होंगे तो एक जर्नल प्रदर्शित किया जाएगा।",
  "diary.pulse_badge": "नाड़ी",
  "diary.safety_desc": "विचारशील शब्दों की संख्या बढ़ी",
  "diary.safety_title": "सुरक्षा की भावना",
  "diary.select_group_sr": "चैट चुनें",
  "diary.subtitle": "धर्मग्रंथों को अद्यतन करने से पहले. अपने विचारों को स्मृति के रूप में रखें।",
  "diary.title": "दिन की गाँठ",
  "invite.error_expired": "यह आमंत्रण लिंक समाप्त हो गया है.",
  "invite.error_join": "भागीदारी विफल रही.",
  "invite.join": "इस कक्षा में शामिल हों",
  "invite.join_group_tpl": "{groupName} से जुड़ें.",
  "invite.joining": "भागीदारी प्रसंस्करण...",
  "invite.loading": "आमंत्रण जानकारी लोड हो रही है...",
  "invite.sign_in": "दाखिल करना",
  "invite.sign_needed": "कृपया भाग लेने के लिए साइन इन करें या साइन अप करें।",
  "invite.sign_up": "नया पंजीकरण",
  "invite.title": "आमंत्रण लिंक",
  "profile.common_change": "परिवर्तन",
  "profile.common_save": "रखना",
  "profile.create_group_button_prefix": "बनाएं(",
  "profile.create_group_button_suffix": "पुण्य उपभोग)",
  "profile.create_group_hint": "यदि आपके पास निश्चित मात्रा में सद्गुण अंक हैं तो आप एक बना सकते हैं।",
  "profile.create_group_placeholder": "उदाहरण: कक्षा 3बी चैट",
  "profile.create_group_title": "नया समूह बनाएं",
  "profile.daily_limit_readonly_prefix": "मौजूदा ऊपरी सीमा",
  "profile.daily_limit_readonly_suffix": "समय/दिन (केवल व्यवस्थापक द्वारा बदला जा सकता है)",
  "profile.daily_limit_title": "दैनिक पोस्टिंग सीमा",
  "profile.edit_badge": "संपादन करना",
  "profile.edit_class_label": "संबंधन",
  "profile.edit_guardian_id_label": "अभिभावक आईडी (@id)",
  "profile.edit_guardian_id_placeholder": "@कोटोनोहा",
  "profile.edit_message_label": "संदेश",
  "profile.edit_name_label": "नाम",
  "profile.edit_title": "प्रोफ़ाइल संपादित करें",
  "profile.error_ai_settings_update": "AI सेटिंग अपडेट करने में विफल.",
  "profile.error_create": "सृजन विफल रहा.",
  "profile.error_daily_limit_update": "पोस्ट सीमा अद्यतन करने में विफल.",
  "profile.error_group_description_update": "समूह विवरण अपडेट करने में विफल.",
  "profile.error_group_rename": "समूह का नाम बदलने में विफल.",
  "profile.error_group_switch": "समूह स्विचिंग विफल रही.",
  "profile.error_invite_create": "आमंत्रण बनाने में विफल.",
  "profile.error_preview": "टोन नमूना उत्पन्न करने में विफल.",
  "profile.error_profile_update": "प्रोफ़ाइल अद्यतन विफल रहा.",
  "profile.error_transfer_admin": "प्रशासनिक विशेषाधिकारों का प्रत्यायोजन विफल रहा।",
  "profile.facilitator_admin_only": "केवल प्रशासक ही एआई फैसिलिटेटर सेटिंग्स बदल सकते हैं।",
  "profile.facilitator_age_label": "आयु (वैकल्पिक)",
  "profile.facilitator_age_placeholder": "उदाहरण: 28",
  "profile.facilitator_bio_label": "अनुपूरक वर्ण सेटिंग्स (वैकल्पिक)",
  "profile.facilitator_bio_placeholder": "उदाहरण: एक एथलीट की पीठ पर एक छोटी सी थपकी। संप्रेषित किए जाने वाले मामलों को स्पष्ट रूप से संप्रेषित करें।",
  "profile.facilitator_enable_label": "इस चैट में AI फैसिलिटेटर सक्षम करें",
  "profile.facilitator_first_person_label": "प्रथम व्यक्ति (वैकल्पिक)",
  "profile.facilitator_first_person_placeholder": "उदाहरण: मैं",
  "profile.facilitator_gender_label": "लिंग (वैकल्पिक)",
  "profile.facilitator_gender_placeholder": "उदाहरण: पुरुष/महिला/सेट नहीं",
  "profile.facilitator_hint": "सेटिंग केवल इस चैट के लिए हैं. नियम निर्णय को प्राथमिकता देता है और केवल स्वर को दर्शाता है।",
  "profile.facilitator_name_label": "नाम",
  "profile.facilitator_name_placeholder": "उदाहरण: लफी सेंसेई",
  "profile.facilitator_preset_disciplined": "अनुशासन प्रकार",
  "profile.facilitator_preset_encouraging": "प्रोत्साहन प्रकार",
  "profile.facilitator_preset_facilitator": "सुविधाप्रदाता प्रकार",
  "profile.facilitator_preset_label": "व्यक्तित्व प्रीसेट",
  "profile.facilitator_preset_watcher": "घड़ी का प्रकार",
  "profile.facilitator_preview_empty": "एक बार जब आप अपनी सेटिंग्स दर्ज कर लेंगे, तो वे यहां दिखाई देंगे।",
  "profile.facilitator_preview_loading": "प्रबंधन AI एक नमूना बना रहा है...",
  "profile.facilitator_preview_title": "स्वर नमूना",
  "profile.facilitator_title": "एआई फैसिलिटेटर सेटिंग्स",
  "profile.facilitator_tone_label": "कैसे बोलें (वैकल्पिक)",
  "profile.facilitator_tone_placeholder": "उदाहरण: विनम्र/फ्रैंक",
  "profile.group_description_admin_only": "समूह विवरण केवल प्रशासकों द्वारा बदला जा सकता है।",
  "profile.group_description_help": "एआई नायकों की टिप्पणियों, निष्कर्षण और सारांश के लिए संदर्भ के रूप में उपयोग किया जाता है।",
  "profile.group_description_placeholder": "उदाहरण: जूनियर हाई स्कूल के दूसरे वर्ष में कक्षा संचार के लिए। प्रस्तुतियाँ, सामान और समूह संचार साझा करने का उद्देश्य।",
  "profile.group_description_title": "समूह विवरण",
  "profile.group_manage_no_joined_group": "ऐसी कोई चैट नहीं है जिसमें आप अभी तक शामिल हुए हों।",
  "profile.group_manage_select_hint": "वह चैट चुनें जिसे आप प्रबंधित करना चाहते हैं.",
  "profile.group_manage_select_title": "प्रबंधित करने के लिए चैट का नाम (पुलडाउन)",
  "profile.group_rename_admin_only": "समूह के नाम केवल प्रशासक ही बदल सकते हैं।",
  "profile.group_rename_title": "समूह का नाम परिवर्तन",
  "profile.group_unjoined": "समूह में भाग नहीं लेना",
  "profile.groups_badge": "समूह",
  "profile.groups_title": "समूह प्रबंधन",
  "profile.invite_admin_only": "आमंत्रण लिंक केवल प्रशासकों द्वारा ही जारी किए जा सकते हैं।",
  "profile.invite_create_button": "आमंत्रण लिंक जारी करें",
  "profile.invite_created_suffix_prefix": "(अधिकतम",
  "profile.invite_created_suffix_suffix": "समय)",
  "profile.invite_max_uses_label": "उपयोग की संख्या",
  "profile.invite_title": "आमंत्रण लिंक",
  "profile.members_empty": "अभी तक कोई सदस्य नहीं है.",
  "profile.members_select_group": "इसके सदस्यों को प्रदर्शित करने के लिए एक समूह का चयन करें।",
  "profile.members_title": "समूह के सदस्यों को",
  "profile.message_badge": "मार्गदर्शन",
  "profile.message_title": "संदेश",
  "profile.points_title": "सद्गुण अंक",
  "profile.post_count_title": "पदों की संख्या",
  "profile.save_profile": "प्रोफ़ाइल बचा",
  "profile.saved_profile": "मेरी प्रोफ़ाइल अपडेट कर दी गई है.",
  "profile.saving_profile": "सहेजा जा रहा है...",
  "profile.select_group_sr": "चैट चुनें",
  "profile.subtitle": "यहां, हम सुखद बातचीत का समर्थन करने की तैयारी करेंगे।",
  "profile.title": "तैयार हो रहे",
  "profile.transfer_admin_admin_only": "केवल प्रशासक ही प्रशासनिक विशेषाधिकार सौंप सकते हैं।",
  "profile.transfer_admin_button": "इस उपयोगकर्ता को सौंपें",
  "profile.transfer_admin_no_candidate": "प्रतिनिधिमंडल के लिए कोई सदस्य उपलब्ध नहीं हैं.",
  "profile.transfer_admin_title": "प्रशासनिक अधिकार सौंपना",
  "profile.weekly_ai_follow": "एआई अनुसरण करता है",
  "profile.weekly_announcement": "महत्वपूर्ण संदेश साझा करना",
  "profile.weekly_badge": "प्रगति",
  "profile.weekly_positive": "सकारात्मक पोस्ट",
  "profile.weekly_title": "इस सप्ताह का प्रक्षेप पथ",
  "sign_in.subtitle": "आमंत्रण लिंक का उपयोग करके जिस कक्षा में आप शामिल हुए थे, उसे मन की शांति के साथ अपना संदेश भेजें।",
  "sign_in.title": "शब्दों का संरक्षक",
  "sign_up.subtitle": "Google या ईमेल पर साइन अप करें और अपनी कक्षा के शब्द रखें।",
  "sign_up.title": "शब्दों का संरक्षक",
};

const LOCALE_OVERRIDES: Record<
  Exclude<UiStringSeed["locale"], "ja">,
  Record<string, string>
> = {
  en: EN_OVERRIDES,
  zh: ZH_OVERRIDES,
  hi: HI_OVERRIDES,
};

const DEFAULT_UI_STRINGS: UiStringSeed[] = [
  ...JA_UI_STRINGS,
  ...(["en", "zh", "hi"] as const).flatMap((locale) =>
    JA_UI_STRINGS.map((row) => ({
      ...row,
      locale,
      text: LOCALE_OVERRIDES[locale][`${row.page}.${row.key}`] ?? row.text,
    }))
  ),
];

const normalizeLocale = (value: string | undefined): UiStringSeed["locale"] => {
  const normalized = value?.trim().toLowerCase();
  if (normalized === "en" || normalized === "zh" || normalized === "hi") {
    return normalized;
  }
  if (normalized?.startsWith("zh")) return "zh";
  if (normalized?.startsWith("hi")) return "hi";
  return "ja";
};

const toDefaultMap = (page: string, locale: UiStringSeed["locale"]) => {
  const map: Record<string, string> = {};
  for (const row of DEFAULT_UI_STRINGS) {
    if (row.page === page && row.locale === locale) {
      map[row.key] = row.text;
    }
  }
  return map;
};

export const getByPage = query({
  args: {
    page: v.string(),
    locale: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const requestedLocale = normalizeLocale(args.locale);
    const defaultMap = toDefaultMap(args.page, requestedLocale);

    const localRows = await ctx.db
      .query("uiStrings")
      .withIndex("by_page_locale", (q) => q.eq("page", args.page))
      .filter((q) => q.eq(q.field("locale"), requestedLocale))
      .collect();

    const fallbackRows =
      requestedLocale === "ja"
        ? []
        : await ctx.db
            .query("uiStrings")
            .withIndex("by_page_locale", (q) => q.eq("page", args.page))
            .filter((q) => q.eq(q.field("locale"), "ja"))
            .collect();

    for (const row of fallbackRows) {
      defaultMap[row.key] = row.text;
    }
    for (const row of localRows) {
      defaultMap[row.key] = row.text;
    }

    return defaultMap;
  },
});

export const seedDefaults = mutation({
  args: {},
  handler: async (ctx) => {
    const now = Date.now();
    let inserted = 0;
    let updated = 0;
    const existingRows = await ctx.db.query("uiStrings").collect();
    const existingMap = new Map(
      existingRows.map((row) => [`${row.page}::${row.key}::${row.locale}`, row])
    );

    for (const item of DEFAULT_UI_STRINGS) {
      const existing = existingMap.get(`${item.page}::${item.key}::${item.locale}`);

      if (existing) {
        if (existing.text !== item.text) {
          await ctx.db.patch(existing._id, {
            text: item.text,
            updatedAt: now,
          });
          updated += 1;
        }
      } else {
        await ctx.db.insert("uiStrings", {
          page: item.page,
          key: item.key,
          locale: item.locale,
          text: item.text,
          updatedAt: now,
        });
        inserted += 1;
      }
    }

    return {
      totalDefaults: DEFAULT_UI_STRINGS.length,
      inserted,
      updated,
    };
  },
});

export const listPages = query({
  args: {},
  handler: async (ctx) => {
    const rows = await ctx.db.query("uiStrings").collect();
    return Array.from(new Set(rows.map((row) => row.page))).sort();
  },
});
